### ISSUE TITLE
Questions - enhancements

### ISSUE THREAD

**Issue by 1oglop1** [mspkvp/tk7movespretty#11]
Hi Mike, this is an amazing project! 
I'm trying to learn some JS but I could never find a good use case until now!
I know some basics of D3JS, however I'm real beginner in JS.

Do you mind guiding me a little bit?
I'd like to try to implement filtering and selection.
There are usually few moves one prefers, so I was thinking about option to select certain moves display just the selection. (probably even save the filter in cookie or so).

I also have few ideas on how to possibly implement user submitted combos. 

So if you could help me to get started it would be awesome!
Thanks.
Jan

**Comment by mspkvp** [comment]
Hey Jan!

Thanks! Il be honest with you, this project as it stands is a bit chaotic
and hard to maintain, I mean, we generate html code by hand. D:
That's one of the reasons I haven't updated it in a long time and decided
to redo-it with a proper framework. But don't let that discourage you!
A "good thing" about this being so simple and vanilla, is that you can
easily download the project and "run it" by opening the index.html file, no
hassle to deal with other tools (although they are super awesome -
watchers, builders, etc).

On to the point, *move away from d3.js *for simple object and DOM handling.
I honestly have no idea why I picked it in the first place, maybe it was
because of TOOLASSISTED using it with his "simple" table based layout and
since my goal was to tweak presentation, I didn't think to much about it.
D3.js is awesome to visualize data, as in ploting graphs, building charts,
etc, but for just handling data it's really excessive to use it. With
ECMAS6 you have all the tools you need for handling whatever you like,
since it ported lots of functionalities from underscore.js. To modify the
DOM, if you don't like accessing it directly with native JS, look into
JQuery (or another on you might find and like). All of these tools have
huge communities and plenty of info around.

In terms of code, you have to filter the array of moves through the each
object fields you want to filter.
Each move follows a structure of which you can check on the character's
files. So first things first, try to understand what each field means and
probably transform each object into something more readable (like the
example in /other/movelist_template.json). Then you want to target the
'fetchmovelist' function (/src/js/scripts.js - line 172) and apply your
filtering there.

If you don't want to bother in changing everything and want to focus just
on filtering, since this project is already lost in terms of good
practices, make a few global variables, for if filtering is enabled, which
fields are being filtered (maybe a filter type?) and apply the restrictions
inside the 'fetchmovelist'  method.
The storage can be done in a similar way that is currently implemented with
the preferences.

Regarding user combo submission, this requires either import/export of a
file functionallity to save it locally or on your browsers cache if it's
only meant to stay client side. If you want to store it in a DB, you might
need a server-side solution and that is another problem to tackle, since
then you need to really pay some attention to security and what not.

I'm currently developing (when I can get some free time) another version
that will feature much more than what this site has, in a more proper and
maintainable fashion and I will make the effort to open it up to
contributions with the necessary management open-source contribution rules.


BUT, if you still want to have a crack at it for the filtering, if you can
build a nice way to filter the moves and comply with the current site for
the fun of it, go for it!
When your done, notify me or just do the pull request, I'll review it and
if everything looks good, I'll merge it! :)

Any other questions you might have, don't hesitate.


Cheers

Jan Gazda <notifications@github.com> escreveu no dia sexta, 12/04/2019 à(s)
06:30:
