### ISSUE TITLE
Standard move notations

### ISSUE THREAD

**Issue by beriah** [mspkvp/tk7movespretty#8]
![85ya3 1](https://user-images.githubusercontent.com/1399263/30182103-e86d2920-9415-11e7-9a8f-954b2d0ecec7.png)

Not sure if you want input and/or feature requests but I think having something like this would be helpful when you need to ctrl+f a specific move without needing to scroll through the whole list.

**Comment by mspkvp** [comment]
Yes I do and thanks tor using this section for it :)

I thought about that and it should be ready this weekend. I was thinking that I would replace the current command display with the standard string if the option was enabled in preferences, instead of having both of them.

What do you think?

**Comment by riesza** [comment]
I'm not sure if both would fit the layout but I think having both would be quite nice. The in-game one for viewing pleasure and the number notation so you can find it quicker.

**Comment by mspkvp** [comment]
Maybe I didn't express myself correctly. Whoops. I still intend to replace the main command to a string as an option. For search purposes, I can add to the filter a search box in which these notations are recognized. I can catch the "ctrl-f"and bind it to the filter's box instead of the general one.

Does it make more sense? Or your point is having the plain string input as another visual aid to find moves easier?

**Comment by riesza** [comment]
Oh I understand now. Yeah a search box that recognizes those notations would be great!
